### ISSUE TITLE
The call connects, but media IP in SDP is 127.0.0.1 and some API errors

### ISSUE THREAD

**Issue by shah-hussain-khattak** [OpenSIPS/opensips-ai-voice-connector-ce#2]
Hi Team, 

Thanks for the help in issue # 1, I can connect the call. But seeing the media IP negotiated by the server is 127.0.0.1 in the final 200 SDP:

**200 OK SDP from Server:**

SIP/2.0 200 OK
Via: SIP/2.0/UDP 218.33.x.x:65057;received=218.33.x.x;rport=65057;branch=z9hG4bKPj6c11ceb13f0544ed97ad05cba919a261
To: <sip:openai@domain.sip>;tag=B2B.97.456.1730413641.425227748
From: <sip:shah@domain.sip>;tag=e7f3a84ad406418da5e593977bfce5e2
Call-ID: 3f38287e99fb4608b5301996723725ab
CSeq: 28638 INVITE
Content-Type: application/sdp
Contact: <sip:52.65.x.x:5060>
Server: OpenSIPS (3.6.0-dev (x86_64/linux))
Content-Length: 187

v=0
o=- 3939438443 3939438443 IN IP4 127.0.1.1
s=pjmedia
t=0 0
m=audio 42738 RTP/AVP 8
**c=IN IP4 127.0.0.1**
a=sendrecv
a=ssrc:401287346 cname:2a432bed342839bf
a=rtpmap:8 PCMA/8000

**From container logs:**

2024-10-31 22:27:22,690 - INFO - handling B2B.97.456.1730413641.425227748 using openai AI
2024-10-31 22:27:22,691 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-8' coro=<Call.send_rtp() done, defined at /app/src/call.py:120> exception=OSError(22, 'Invalid argument')>
Traceback (most recent call last):
  File "/app/src/call.py", line 153, in send_rtp
    self.serversock.sendto(bytes.fromhex(rtp_packet),
OSError: [Errno 22] Invalid argument
2024-10-31 22:27:23,716 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-7' coro=<OpenAI.start() done, defined at /app/src/openai_api.py:67> exception=ConnectionClosedError(Close(code=3003, reason='invalid_request_error.access_not_enabled'), Close(code=3003, reason='invalid_request_error.access_not_enabled'), True)>
Traceback (most recent call last):
  File "/app/src/openai_api.py", line 81, in start
    await self.ws.send(json.dumps({"type": "session.update",
  File "/usr/local/lib/python3.10/site-packages/websockets/asyncio/connection.py", line 403, in send
    async with self.send_context():
  File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/site-packages/websockets/asyncio/connection.py", line 873, in send_context
    raise self.protocol.close_exc from original_exc
websockets.exceptions.ConnectionClosedError: received 3003 (registered) invalid_request_error.access_not_enabled; then sent 3003 (registered) invalid_request_error.access_not_enabled
2024-10-31 22:27:26,182 - INFO - Call B2B.97.456.1730413641.425227748 closing

2024-10-31 22:28:20,825 - INFO - handling B2B.92.226.1730413699.680774186 using deepgram AI
2024-10-31 22:28:20,844 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-12' coro=<Call.send_rtp() done, defined at /app/src/call.py:120> exception=OSError(22, 'Invalid argument')>
Traceback (most recent call last):
  File "/app/src/call.py", line 153, in send_rtp
    self.serversock.sendto(bytes.fromhex(rtp_packet),
OSError: [Errno 22] Invalid argument
2024-10-31 22:28:27,080 - INFO - Call B2B.92.226.1730413699.680774186 closing

I made some changes in the call.py script, so the media IP stays my server's public IP, the results after that were:

**200 OK SDP from Server:**

SIP/2.0 100 Giving it a try
Via: SIP/2.0/UDP 218.33.x.x:65057;received=218.33.x.x;rport=65057;branch=z9hG4bKPjd386ff32eca042b496ef26b7192217fd
To: <sip:openai@domain.sip>
From: <sip:shah@domain.sip>;tag=a3cd743926c449ae82c94a2696dd8c32
Call-ID: 39bf5359a1504a62bff24c13ca7aec47
CSeq: 5819 INVITE
Server: OpenSIPS (3.6.0-dev (x86_64/linux))
Content-Length: 0

SIP/2.0 200 OK
Via: SIP/2.0/UDP 218.33.x.x:65057;received=218.33.x.x;rport=65057;branch=z9hG4bKPjd386ff32eca042b496ef26b7192217fd
To: <sip:openai@domain.sip>;tag=B2B.139.188.1730414032.226335194
From: <sip:shah@domain.sip>;tag=a3cd743926c449ae82c94a2696dd8c32
Call-ID: 39bf5359a1504a62bff24c13ca7aec47
CSeq: 5819 INVITE
Content-Type: application/sdp
Contact: <sip:52.65.x.x:5060>
Server: OpenSIPS (3.6.0-dev (x86_64/linux))
Content-Length: 193

v=0
o=- 3939438833 3939438833 IN IP4 52.65.x.x
s=pjmedia
t=0 0
m=audio 33337 RTP/AVP 8
**c=IN IP4 52.65.x.x**
a=sendrecv
a=ssrc:240060329 cname:67012b835e406231
a=rtpmap:8 PCMA/8000

**From container logs:**

2024-10-31 22:33:52,486 - INFO - handling B2B.139.188.1730414032.226335194 using openai AI
2024-10-31 22:33:52,488 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-4' coro=<Call.send_rtp() done, defined at /app/src/call.py:100> exception=OSError(22, 'Invalid argument')>
Traceback (most recent call last):
  File "/app/src/call.py", line 133, in send_rtp
    self.serversock.sendto(bytes.fromhex(rtp_packet),
OSError: [Errno 22] Invalid argument
2024-10-31 22:33:53,397 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-3' coro=<OpenAI.start() done, defined at /app/src/openai_api.py:67> exception=ConnectionClosedError(Close(code=3003, reason='invalid_request_error.access_not_enabled'), Close(code=3003, reason='invalid_request_error.access_not_enabled'), True)>
Traceback (most recent call last):
  File "/app/src/openai_api.py", line 81, in start
    await self.ws.send(json.dumps({"type": "session.update",
  File "/usr/local/lib/python3.10/site-packages/websockets/asyncio/connection.py", line 403, in send
    async with self.send_context():
  File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/site-packages/websockets/asyncio/connection.py", line 873, in send_context
    raise self.protocol.close_exc from original_exc
websockets.exceptions.ConnectionClosedError: received 3003 (registered) invalid_request_error.access_not_enabled; then sent 3003 (registered) invalid_request_error.access_not_enabled
2024-10-31 22:33:57,566 - INFO - Call B2B.139.188.1730414032.226335194 closing

2024-10-31 22:34:05,809 - INFO - handling B2B.398.253.1730414044.550927147 using deepgram AI
2024-10-31 22:34:05,811 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-8' coro=<Call.send_rtp() done, defined at /app/src/call.py:100> exception=OSError(22, 'Invalid argument')>
Traceback (most recent call last):
  File "/app/src/call.py", line 133, in send_rtp
    self.serversock.sendto(bytes.fromhex(rtp_packet),
OSError: [Errno 22] Invalid argument
2024-10-31 22:34:09,881 - INFO - Call B2B.398.253.1730414044.550927147 closing

Can you please share some suggestions/ideas on how to fix this? Am I missing something from the configuration point of view? 

Thank you! 

Regards, 
Shah Hussain

**Comment by razvancrainea** [comment]
You should not have to modify the code, you can simply set the IP in the SDP through the [`rtp_ip` setting](https://github.com/OpenSIPS/opensips-ai-voice-connector-ce/blob/main/docs/config.md#global-parameters). If you do it like so, does it have the same behavior?

**Comment by shah-hussain-khattak** [comment]
Hi Razvan, 

I set up the parameters as you mentioned, but for some reason, the SDP is sending 127.0.0.1 IP for media:

These are my settings:

root@ip-172-16-8-193:/usr/src/opensips-ai-voice-connector-ce/docker# more config.ini
[opensips]
ip = 127.0.0.1
port = 8080

[engine]
event_ip = 127.0.0.1
rtp_ip=52.65.xx.xx


[deepgram]
disabled = false

[openai]
disabled = false

root@ip-172-16-8-193:/usr/src/opensips-ai-voice-connector-ce/docker# more .env
DEEPGRAM_API_KEY=
OPENAI_API_KEY=sk-proj-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
MI_IP=127.0.0.1
MI_PORT=8080
root@ip-172-16-8-193:/usr/src/opensips-ai-voice-connector-ce/docker#


root@ip-172-16-8-193:/usr/src/opensips-ai-voice-connector-ce/docker# more docker-compose.yml
services:
  engine:
    container_name: ai-voice-connector-engine
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    network_mode: host
    environment:
      CONFIG_FILE: config.ini
    env_file:
      - .env
    volumes:
      - ../src:/app/src/

  opensips:
    container_name: ai-voice-connector-opensips
    image: opensips/opensips:latest
    volumes:
      - ../cfg/:/etc/opensips/
    network_mode: host


The SDP sent is:

v=0
o=- 3939530862 3939530862 IN IP4 127.0.1.1
s=pjmedia
t=0 0
m=audio 46990 RTP/AVP 8
c=IN IP4 127.0.1.1
a=sendrecv
a=ssrc:2053979861 cname:4fbb0d8b65557ff9
a=rtpmap:8 PCMA/8000


Please advise me, on what I am missing.

Thank you!

**Comment by razvancrainea** [comment]
For some reason, the config file is not picked up by the engine. There was a fix for this, can you pull the latest source code? If not, try to export the `RTP_IP` variable in your environment.

**Comment by vaestvita** [comment]
> were you able to get this to work?

hi, your question is not addressed to me, but since it works for me
my main PBX is on Asterisk
I launched a voice connector on a separate server specifying RTP_IP (external address of the voice connector server)
and created a point-to-point trunk in Asterisk

```
[opesips]
type=aor
qualify_frequency=0
contact=sip:voice_connector_ip:5060

[opesips]
type=identify
endpoint=opesips
match=voice_connector_ip

[opesips]
type=endpoint
transport=0.0.0.0-udp
context=from-pstn
disallow=all
allow=ulaw,alaw
aors=opesips
send_connected_line=no
rtp_keepalive=0
language=en
user_eq_phone=no
t38_udptl=no
t38_udptl_ec=none
fax_detect=no
trust_id_inbound=no
t38_udptl_nat=no
direct_media=no
rtp_symmetric=yes
dtmf_mode=auto
```
and then for example you can do it like this

```
[opensips]
exten => 5555,1,Dial(PJSIP/opesips/sip:openai@voice_connector_ip:5060)
    same => n,Hangup()
```

that is, when calling 5555 the call is routed to
openai@voice_connector_ip:5060

**Comment by hasanr68** [comment]
@vaestvita - thanks a lot for taking the time to respond. Much appreciated, I think the impact of your suggestion ends up like a dbalias in Opensips. The call to 5555 is redirecting to openai@voice_connector_ip:5060, when it should go to realtime. I also noticed that although uac_auth exists in the modules folder, I get a warning that isn't loading.

**Comment by vaestvita** [comment]
@hasanr68 You don’t need to create the `openai` user since it is not a SIP user but rather some kind of alias. The `get_to` function extracts it from the SIP `TO` header (e.g., `sip:openai@voice_connector_ip:5060`) and then selects the appropriate flavor (in this case, `openai`). 

By the way, you don’t even need to direct the call specifically to `openai@voice_connector_ip`. You can route the call to any random extension (e.g., `12345@voice_connector_ip`). 

If you specify only the OpenAI key in `.env` and set `DEEPGRAM_DISABLE=yes`, the `get_ai_flavor_default` function will return the OpenAI flavor and connect your call to the OpenAI server.

**Comment by hasanr68** [comment]
Hi again.
Thanks a lot. I have tried all the possibilities you mention. Just removed openai as an alias and I get "Bad extension" response (standard opensips.cfg error if a user is not found).

**Comment by hasanr68** [comment]
Finally an error :)
 ERROR:mi_datagram:mi_datagram_callback: cannot parse command: INVITE sip:openai@127.0.0.1:8080

**Comment by Vince-0** [comment]
Specifying `RTP_IP=` to my public IP in .env allowed the audio through and no more error message displaying like this:
`ai-voice-connector-engine    | ConnectionClosed in AbstractAsyncWebSocketClient._listening with code 1011: Deepgram did not receive audio data or a text message within the timeout window. See https://dpgr.am/net0001 ...<snipped>`

**Comment by razvancrainea** [comment]
So is this issue resolved? can we close the ticket?
